from httpd
run apt update -y
run apt install wget unzip -y
run wget https://www.free-css.com/assets/files/free-css-templates/download/page295/finter.zip
run unzip finter.zip
run cp -rvf finter-html/* /usr/local/apache2/htdocs/
