from httpd
run apt update -y
run apt install git unzip wget -y
run git clone https://github.com/bedimcode/responsive-website-restaurant.git
run cp -rvf responsive-website-restaurant/* /usr/local/apache2/htdocs/
 
