from nginx
run apt-get update -y
run apt-get install wget unzip vim -y
run wget https://www.free-css.com/assets/files/free-css-templates/download/page294/artxibition.zip
run unzip artxibition.zip
run cp -rvf 2125_artxibition/* /usr/share/nginx/html/
 
